# Generated by Django 6.0 on 2025-12-30 06:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grievance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='grievance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='grievance.grievance'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='grievance',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='grievance.grievance'),
        ),
        migrations.AlterField(
            model_name='grievance',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_grievances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='officer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='officer_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
