# Generated by Django 6.0 on 2025-12-31 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grievance', '0002_alter_attachment_grievance_alter_feedback_grievance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='officer',
            name='email',
        ),
        migrations.AddField(
            model_name='officer',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='officers', to='grievance.category'),
        ),
    ]
