# Generated by Django 6.0 on 2025-12-31 17:08

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grievance', '0004_grievance_due_date_grievance_officer_remark_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='grievance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='grievance.grievance'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='grievance',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='grievance.grievance'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='rating',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='grievance',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grievances', to='grievance.category'),
        ),
        migrations.AlterField(
            model_name='grievance',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grievances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='grievanceassignment',
            name='assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_by_me', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='grievanceassignment',
            name='grievance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='grievance.grievance'),
        ),
        migrations.AlterField(
            model_name='grievanceassignment',
            name='officer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_grievances', to='grievance.officer'),
        ),
        migrations.AlterField(
            model_name='grievancestatushistory',
            name='changed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status_changes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='grievancestatushistory',
            name='grievance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='grievance.grievance'),
        ),
    ]
