# Generated by Django 6.0.1 on 2026-01-07 18:13

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grievance', '0007_alter_grievance_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grievance',
            options={},
        ),
        migrations.AlterModelOptions(
            name='grievancestatushistory',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='grievanceassignment',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(upload_to='attachments/'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='rating',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='grievance',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grievances', to='grievance.category'),
        ),
        migrations.AlterField(
            model_name='grievance',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='grievance',
            name='escalation_level',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='grievance',
            name='last_escalated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='grievance',
            name='priority',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], db_index=True, default='Medium', max_length=20),
        ),
        migrations.AlterField(
            model_name='grievance',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Resolved', 'Resolved')], db_index=True, default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='grievancestatushistory',
            name='changed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status_changes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='officer',
            name='department',
            field=models.CharField(max_length=100),
        ),
    ]
